### PR TITLE
Resetting Variant ID when new variants are generated

### PR DESCRIPTION
**Pull request by phyninja**
I have not been able to replicate the behavior mentioned in #833 after making the change attached.

### CODE REVIEW

**Review by shahthepro — COMMENTED** [review]
Thanks for finding and fixing this bug. Is this PR ready to be merged? Or do you want to take some time doing more tests?

**Comment by phyninja** [comment]
If afforded the luxury, it would be best to verify that this doesn't break anything on the back end.

**Comment by phyninja** [comment]
@shahthepro
Update: 
My ignorance about the Printful platform disallows an understanding of the code in dshop/backend/logic/printful/sync/writeProductData.js

I have reviewed the use of variant.id in the following files, and am okay with this change in relation to them:
dshop/shop/src/pages/Product.js
dshop/backend/logic/products/index.js
dshop/shop/src/themes/ybm/components/Product.js
dshop/shop/src/utils/useProduct.js
dshop/shop/src/utils/useAdminProduct.js
dshop/shop/src/utils/useProducts.js

**Comment by phyninja** [comment]
I'm ready for this PR to be merged. My belief is that generateVariants.js only applies to products managed via the DShop platform. Furthermore, [DShop's welcome packet](https://drive.google.com/file/d/1_O8nylYyNh23O9vSnWmkIniiMOXSz9Ql/view) mentions:
> Dshop does not support both Printful and non-Printful products at the same time. If there are non-Printful products in the store, sync-ing a Printful account will cause those products to be lost.

**Comment by shahthepro** [comment]
Thanks @phyninja, Yeah, we don't override variant ID of printful products. It must be unique already.

**Pull request merged**
