### PR TITLE
Enhancement to address issue #506

### PR DESCRIPTION
**Pull request by phyninja**

### CODE REVIEW

**Comment by phyninja** [comment]
In its current form, the CSV shows the quantity of items as shown in the screenshot below

CSV Enhancement

One may notice that immediately that certain product IDs are repeated. This is because those orders contain 'Variants' of the same product.

**Review by franckc — APPROVED** [review]
Looks good to me! Thank you for your contribution :)

**Comment by franckc** [comment]
@phyninja Nice work. I merged your code in the master branch. It is going to get automatically deployed to our staging environment within a few minutes after the merge. If you get a chance, please do a quick test on staging: https://rinkebyapi.ogn.app/ to confirm that things are working as expected.

Next time we deploy to production, your change will go live! :)

**Comment by phyninja** [comment]
Test complete. Results are as expected.

**Comment by franckc** [comment]
Excellent. Thanks for testing @phyninja :) You rock!

**Pull request merged**
