### PR TITLE
DB migration to remove unused tables

### PR DESCRIPTION
**Pull request by ZaHuPro**
Related Issue: #747

### CODE REVIEW

**Review by mikeshultz — CHANGES_REQUESTED** [review]
There's still references to the `OldOrder` and `ShopDeploymentName` model stills in the codebase.  

@franckc, if we really want to roll this soon, Let's make sure we get a good backup before deploying this.  At least of `shop_deployment_names`.

**Comment by franckc** [comment]
> There's still references to the `OldOrder` and `ShopDeploymentName` model stills in the codebase.
> 
> @franckc, if we really want to roll this soon, Let's make sure we get a good backup before deploying this. At least of `shop_deployment_names`.

@mikeshultz Yes, good idea. I'll handle that before the rollout to prod.

**Comment by franckc** [comment]
@ZaHuPro Nice work. Please look for "OldOrders" and "ShopDeploymentName" in the codebase to remove references to it (note: it's fine to delete the script offchainOrdersMigration.js). Thank you!

**Comment by ZaHuPro** [comment]
@franckc  I have removed all the reference of the unused models

**Review by franckc — APPROVED** [review]
LGTM

**Pull request merged**
