### PR TITLE
Adds pipeline to build and deploy generic UI

### PR DESCRIPTION
**Pull request by mikeshultz**
- Example builds.json: https://storage.cloud.google.com/dshop-ui-staging/builds.json
- Bucket contents: https://console.cloud.google.com/storage/browser/dshop-ui-staging;tab=objects?forceOnBucketsSortingFiltering=false&project=origin-214503&prefix=
- Deployed IPNS contents: https://ui.ogn.app/
- Deployed IPFS contenst: https://ipfs.io/ipfs/QmZ3v5JUmWZByXU8kmJsBDvVELgs2USQJdxkDvmmLHjrm5

(builds.json and bucket contents don't currently match because of my weird testing but they will)

With this proposed solution, an `index.html` build would load builds.json, use the latest hash to load the latest assets.  I haven't built and tested that yet.

Ref #180

### CODE REVIEW

**Comment by mikeshultz** [comment]
The example IPFS deployment linked above appears to be missing the old builds.  Will need to update the script to sync with the CS bucket before deploy.

**Comment by nick** [comment]
Nice, looking good so far :-)

What is the purpose of the old hashes in builds.json? We don't just need the latest hash?

**Comment by mikeshultz** [comment]
Old hashes in the JSON file are probably not going to be used by the FE.  Unless there's some use case down the road I'm not thinking of.  Those builds should reflect what is available in the ui.ogn.app IPFS directory though, and the build pipeline references it to know what to GC.  

Perhaps the FE may want to know its build age?  Just speculating.

We could make this a little easier for the FE bootstrapper though and just add a text file called `LATEST` or whatever with the latest build hash.  Save a few bytes.

**Comment by mikeshultz** [comment]
Going to merge this after lunch so I can test live cloudbuild.   LMK if you want to see any changes.

**Comment by nick** [comment]
Sounds good. Have the UI piece in #459

**Pull request merged**
