### PR TITLE
Reading material for new merchants

### PR DESCRIPTION
**Pull request by phyninja**
Preview:

Onboarding - Admin UI

### CODE REVIEW

**Comment by franckc** [comment]
@phyninja Awesome! Thanks for adding that. Could you take a look at the lint error?

@micahalcorn or @gullible1 : could you confirm those links are the latest that we should use:
https://drive.google.com/file/d/1_O8nylYyNh23O9vSnWmkIniiMOXSz9Ql/view
https://help.originprotocol.com/hc/en-us/categories/360004346733-Dshop

**Comment by franckc** [comment]
@micahalcorn or @gullible1 friendly ping :)

**Comment by gullible1** [comment]
@franckc sorry for the late response, yes those are the 2 links (: We will need to update the welcome pack every now and then though as the product evolves.

**Comment by franckc** [comment]
Thanks @gullible1 ! :)

**Pull request merged**
